# Generated by Django 3.2.4 on 2021-06-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_tips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddittip',
            name='type',
        ),
        migrations.AddField(
            model_name='reddittip',
            name='claimed',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reddittip',
            name='returned',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reddittip',
            name='sent',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
