# Generated by Django 3.2.4 on 2021-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_tips', '0003_auto_20210608_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddittip',
            name='coin_amount',
            field=models.CharField(max_length=30),
        ),
    ]
