# Generated by Django 3.2.4 on 2021-08-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_tips', '0006_reddittip_unclaimed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddittip',
            name='claimed',
        ),
        migrations.RemoveField(
            model_name='reddittip',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='reddittip',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='reddittip',
            name='unclaimed',
        ),
        migrations.AddField(
            model_name='reddittip',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
