# Generated by Django 3.2.4 on 2021-08-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_tips', '0006_reddittip_unclaimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reddittip',
            name='status',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
