# Generated by Django 3.2.4 on 2021-08-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_tips', '0007_reddittip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddittip',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
