# Generated by Django 3.2.4 on 2021-08-30 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_tips', '0008_alter_reddittip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddittip',
            name='claimed',
        ),
        migrations.RemoveField(
            model_name='reddittip',
            name='returned',
        ),
        migrations.RemoveField(
            model_name='reddittip',
            name='sent',
        ),
        migrations.RemoveField(
            model_name='reddittip',
            name='unclaimed',
        ),
    ]
